name: "Publish to PyPI"

on:
  release:
    types: [published]
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/publish.yaml"
      - "pyproject.toml"
      - "CMakeLists.txt"

jobs:
  build_sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v7
        with:
          name: dist-sdist
          path: dist/*.tar.gz

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-15-intel, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v7

      - uses: pypa/cibuildwheel@v4.2.1

      - uses: actions/upload-artifact@v7
        with:
          name: dist-wheels-${{ matrix.os }}
          path: wheelhouse/*.whl

  publish:
    name: Publish to PyPI
    needs: [build_sdist, build_wheels]
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    environment:
      name: pypi
      url: https://pypi.org/p/epiworldpy
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v8
        with:
          pattern: dist-*
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
